### ISSUE TITLE
Recreate test and train partitions for comparability

### ISSUE THREAD

**Issue by oskoller** [tannonk/ma#8]
It is currently not possible to recreate your used test and train partitioning. I cannot find the json file used for that anywhere in the repo.

`/home/ubuntu/data/archimob_r2/meta_info/test_set.json`

Can you point me to where I can find this file?

Thanks a lot!

**Comment by tannonk** [comment]
I've just uploaded the relevant json files to the `archimob/` directory e.g. `archimob/test_set_utts.json`.

Depending on what you are trying to do, it may be best to create new dev/test splits. The original splits don't take speaker IDs into consideration. But in standard ASR setups, the test set should contain only utterances from 'unseen' speakers.

**Comment by oskoller** [comment]
Cool thanks. Is that the same partition as used by your colleague https://github.com/yunigma/Kaldi-for-ASR-of-Swiss-German ?

**Comment by tannonk** [comment]
It should be. I believe that repo is also more up to date than this one so it's probably a better starting point. Hopefully I'll find the time to clean this one up at some point soon.

**Comment by tannonk** [comment]
Just an update, I've cleaned up the master branch and also added the train/dev/test csv files along with some other metadata in json format. See `data`.
